### ISSUE TITLE
[Bug] setSkillPermissions returns spurious 403 when org memberships are unresolved (follow-up to #815)

### ISSUE THREAD

**Issue by chronoai-shining** [ChronoAIProject/Ornn#842]
## Summary (availability regression from #815)

#815 made `setSkillPermissions` reject (403 `not_org_member`) sharing a skill into any org in `sharedWithOrgs` the caller is not a member of. The caller's memberships come from `readUserOrgMemberships(c)`, which **fails soft to `[]`** when the NyxID lookup errors OR the user's access token isn't forwarded (the documented `forward_access_token=false` case → `/me/orgs` returns 200 with `duration:0` → empty memberships).

Pre-#815, an empty membership list only suppressed READ visibility (additive, safe). Post-#815, the SAME empty list drives a WRITE rejection: a legitimate owner re-sharing into an org they truly belong to gets a spurious `403 not_org_member` with a misleading "you are not a member" message whenever NyxID hiccups or their token isn't forwarded. It fails CLOSED (never reopens the CWE-862 leak), so this is an availability/UX bug, not a security hole.

## Acceptance criteria
- [ ] Distinguish "membership lookup unresolved" (forwarded token absent / NyxID lookup errored) from "resolved: caller is genuinely not a member". The membership read (`readUserOrgMemberships` or the actor it builds) must signal which case occurred.
- [ ] On the UNRESOLVED branch, `setSkillPermissions` returns a retryable `503 org_membership_unavailable` (not `403 not_org_member`); the resolved-not-member branch keeps `403 not_org_member`.
- [ ] The existing READ-path callers of `readUserOrgMemberships` (visibility filtering) keep their current fail-soft-to-`[]` behavior (or are reviewed for the same coupling) — do not regress read visibility.
- [ ] Tests: unresolved memberships → 503 (retryable); resolved-not-member → 403; a multi-org partial share (one org the caller belongs to + one they don't) still rejects atomically and names only the denied org id (pins the intersection / all-or-nothing semantics, hardening deferred from #815); the 403 message names the offending org id.

## Metadata
Severity: P3 · availability/UX (fails closed) · Source: /auto consensus review of #815. Related to #815. See [[reference_nyxid_forward_access_token]] behavior.
